login:
    path: /login
    controller: App\Controller\Application::index

login_check:
    path: /login_check

logout:
    path: /logout
    
appConfig:
    path: /config
    controller: App\Controller\Application::config
    methods: GET   

demandsList:
    path: /demandslist/{offset}
    controller: App\Controller\Demands::list
    methods: GET
    defaults: 
        offset: 0
    requirements:
        offset: \d+

demands:
    path: /demands
    controller: App\Controller\Application::index
    methods: GET
    
demandCreatePochtaOrder:
    path: /demands/createpochtaorder
    controller: App\Controller\Demands::createPochtaOrder
    methods: POST    

main:
    path: /
    controller: App\Controller\Application::index
