login:
    path: /login
    controller: App\Controller\Application::index

login_check:
    path: /login_check

logout:
    path: /logout
    
appConfig:
    path: /config
    controller: App\Controller\Application::config
    methods: GET   

demandsList:
    path: /demandslist
    controller: App\Controller\Demands::list
    methods: GET    

demands:
    path: /demands
    controller: App\Controller\Application::index

main:
    path: /
    controller: App\Controller\Application::index
